cmp -l pa5.cpp ~/Downloads/ilu/pa5.cpp
cmp -l hash_function.cpp ~/Downloads/ilu/hash_function.cpp
cmp -l hash_function.h ~/Downloads/ilu/hash_function.h
cmp -l hash_table.h ~/Downloads/ilu/hash_table.h
cmp -l hash_table.cpp ~/Downloads/ilu/hash_table.cpp
cmp -l bloom_filter.cpp ~/Downloads/ilu/bloom_filter.cpp
cmp -l bloom_filter.h ~/Downloads/ilu/bloom_filter.h
cmp -l graph.cpp ~/Downloads/ilu/graph.cpp
cmp -l graph.h ~/Downloads/ilu/graph.h